import { createRoot } from 'react-dom/client'
import App from './App'
import './styles/tokens.css'
import './styles/app.css'
import './sections/Process/Process.css'
import './sections/Compare/Compare.css'
import './sections/Cta/Cta.css'
import './sections/UseCases/UseCases.css'
import './styles/generated-layout.css'
import './sections/Features/Features.css'
import './sections/Roadmap/Roadmap.css'
import './components/RequestToResult/RequestToResult.css'
import './components/BriefToMaterials/BriefToMaterials.css'
import './components/Testimonials/Testimonials.css'
import './components/Pricing/Pricing.css'
import './components/ContactForm/ContactForm.css'
import './sections/Faq/Faq.css'
import './components/Hero/Hero.css'
import './sections/Logos/Logos.css'
import './styles/font-face.css'
import './styles/motion.css'
import './styles/overrides.css'

createRoot(document.getElementById('root')).render(<App />)
